/* Body file for function Actuator
 * Generated by TASTE on 2021-08-27 11:09:10
 * You can edit this file, it will not be overwritten
 * Provided interfaces : work
 * Required interfaces : result
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 184359 61852 238407 128731
 * Timers              :
 */

#include "actuator.h"
#include <stdio.h>

void actuator_startup(void)
{
}

void actuator_PI_work
      (const asn1SccLargeUint32 *IN_a)

{
    printf("Actuator - got work\n");
    static asn1SccBigParameter data;
    int i;
    data.x = *IN_a;
    for(i = 0; i < 262144; ++i)
    {
        data.y.arr[i] = i * *IN_a;
    }
    actuator_RI_result(&data);
    printf("Actuator - result sent\n");
}
