
/* Header file for function Actuator in C language
 * Generated by TASTE on 2021-12-07 19:44:23
 * Context Parameters present : NO
 * Provided interfaces : ping, task_a_acn, task_a_native, task_a_uper, task_b_acn, task_b_native, task_b_uper
 * Required interfaces : pong, result
 * User-defined properties for this function:
  *  |_ TASTE::Is_Component_Type = false
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void actuator_startup(void);

/* Provided interfaces */
void actuator_PI_ping( void );
void actuator_PI_task_a_acn( const asn1SccBigParameter * );
void actuator_PI_task_a_native( const asn1SccBigParameter * );
void actuator_PI_task_a_uper( const asn1SccBigParameter * );
void actuator_PI_task_b_acn( const asn1SccSmallParameter * );
void actuator_PI_task_b_native( const asn1SccSmallParameter * );
void actuator_PI_task_b_uper( const asn1SccSmallParameter * );

/* Required interfaces */
extern void actuator_RI_pong( void );
extern void actuator_RI_result( const asn1SccLargeUint32 * );


#ifdef __cplusplus
}
#endif
