--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (kazoo/templates/skeletons/ada-ri-source/function.tmplt)
with Samv71_Ada_Dataview; use Samv71_Ada_Dataview;
with Taste_Basictypes;    use Taste_Basictypes;
with System_Dataview;     use System_Dataview;
with adaasn1rtl;
with System_Dataview; use System_Dataview;  --  contains definition of the PID type

package Ponger_RI is

   procedure Pong (Pongarg : in out asn1SccMyinteger; Dest_PID : asn1sccPID := asn1sccEnv);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "ponger_check_queue";

   procedure Get_Sender (Sender : out asn1sccPID; Dest_PID : asn1SccPID := asn1sccEnv)
      with Import, Convention => C, Link_Name => "ponger_get_sender";

end Ponger_RI;
