--  Generated by TASTE  (kazoo/templates/skeletons/ada-source/function.tmplt)
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Samv71_Ada_Dataview; use Samv71_Ada_Dataview;
with Taste_Basictypes;    use Taste_Basictypes;
with System_Dataview;     use System_Dataview;

-- Access to required interfaces is specified in this package:
with Ponger_RI; use Ponger_RI;

package Ponger is


   procedure Ping (Pingarg : in out asn1SccMyinteger)
      with Export,
           Convention => C,
           Link_Name  => "ponger_PI_Ping";

end Ponger;
