/* Header file for function Actuator
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void actuator_startup(void);

/* Provided interfaces */
void actuator_PI_ping( const asn1SccMyInteger * );

/* Required interfaces */
extern void actuator_RI_pong( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
