/* Body file for function Actuator
 * Generated by TASTE on 2021-11-30 16:49:08
 * You can edit this file, it will not be overwritten
 * Provided interfaces : task_a, task_b
 * Required interfaces : report_a, report_b
 * User-defined properties for this function:
 *   |_ TASTE::Is_Component_Type = false
 * Timers              : 
 */

#include "actuator.h"

static asn1SccCustomInteger response;

void actuator_startup(void)
{
    response = 0;
}

void actuator_PI_task_a
      (const asn1SccCustomParameter *IN_task_data)

{
   response = IN_task_data->a;
   actuator_RI_report_a(&response);
}
void actuator_PI_task_b
      (const asn1SccCustomParameter *IN_task_data)

{
    response = IN_task_data->b;
    actuator_RI_report_b(&response);
}


