/* Body file for function Controller
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "controller_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




unsigned controller_initialized = 0;
void init_controller(void)
{
   if (0 == controller_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      controller_initialized = 1;
      // Call user code startup function
      extern void controller_startup(void);
      controller_startup();
      puts ("[TASTE] Initialization completed for function Controller");
      controller_initialized = 2;
   }
}
void controller_pong
      (const char *IN_pong, size_t IN_pong_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controller,pong,%lld\n", msc_time);
      fflush(stdout);
   }
   
   static asn1SccMyInteger IN_PONG;
   asn1SccMyInteger_Initialize(&IN_PONG);

   if (0 != Decode_UPER_MyInteger (&IN_PONG, (void *)IN_pong, IN_pong_len)) {
      puts("Error decoding MyInteger in function Controller_pong");
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void controller_PI_pong
      (const asn1SccMyInteger *);





   // Call user code
   controller_PI_pong (&IN_PONG);

}




void controller_tick()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controller,tick,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void controller_PI_tick(void);
   controller_PI_tick();
   // puts ("controller_tick called");
}

