/* Body file for function Controller
 * Generated by TASTE on 2022-10-07 13:40:16
 * You can edit this file, it will not be overwritten
 * Provided interfaces : pong, tick
 * Required interfaces : ping
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "controller.h"
#include <stdio.h>


void controller_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
    puts ("[Controller] Startup");
}

void controller_PI_pong
      (const asn1SccMyInteger *IN_pong)

{
    printf("Pong: %" PRId64 "\n", *IN_pong);
}


void controller_PI_tick(void)
{
    static asn1SccMyInteger tick = 0;

    printf("Ping: %" PRId64 "\n", tick);

    controller_RI_ping(&tick);

    tick++;
}


